### ISSUE TITLE
Create an extension pack for popular validation rules.

### ISSUE THREAD

**Issue by mr5z** [mr5z/PropertyValidator#3]

**Comment by butler1233** [comment]
Definitely this. Adding all the ones on the readme into the package by default would make sense because with those people would be able to just use the validation methods without even having to write their own rules.

**Comment by mr5z** [comment]
Validation rules has been created [here](https://github.com/mr5z/PropertyValidator.ValidationPack).
Needs to update the README of this on how to use it.

**Comment by mr5z** [comment]
Updated the README and added a link to the ValidationPack. Closing this issue now
